### ISSUE TITLE
Tried to close all scratchpads

### ISSUE THREAD

**Issue by birdo-birdson** [MythicPalette/Wordsmith-DalamudPlugin#54]
{"Version":"1.15.1.0","Type":"Wordsmith.Gui.SettingsUI","Namespace":"","WindowName":"Wordsmith - Settings","IsFocused":"True","RespectCloseHotkey":"True","DisableWindowSounds":"False","OnOpenSfxId":"23","OnCloseSfxId":"24","Position":"","PositionCondition":"None","Size":"","SizeCondition":"None","SizeConstraints":"Dalamud.Interface.Windowing.Window\u002BWindowSizeConstraints","Collapsed":"","CollapsedCondition":"None","Flags":"NoScrollbar, NoScrollWithMouse","ForceMainWindow":"False","BgAlpha":"","ShowCloseButton":"True","AllowPinning":"True","AllowClickthrough":"True","TitleBarButtons":"{ \u0022\u0022 }","IsOpen":"False","_newMarkerHeaderOpen":"False","_showAdvancedSettings":"False","_neverShowNotices":"False","_lastSeenNotice":"818761a7-cb39-42f2-b33c-5734594b1207","_searchHistoryCountChange":"10","_researchToTopChange":"True","_trackWordStats":"True","_autoClear":"False","_deleteClosed":"True","_confirmDeleteClosed":"True","_ignoreHypen":"True","_showChunks":"True","_onSentence":"True","_detectHeader":"True","_oocOpening":"(( ","_oocClosing":" ))","_oocByDefault":"False","_sentenceTerminators":".?!","_encapTerminators":"\u0022\u0027*-","_chunkMarkers":"{ \u0022\u0022 }","_newMarker":"{{\u0022Version\u0022, 1.15.1.0}, {\u0022Type\u0022, Wordsmith.ChunkMarker}, {\u0022Position\u0022, AfterOOC}, {\u0022RepeatMode\u0022, All}, {\u0022DisplayMode\u0022, WithMultipleChunks, AnyOOC}, {\u0022Nth\u0022, 1}, {\u0022StartPosition\u0022, 1}, {\u0022Text\u0022, }, {\u0022_position\u0022, AfterOOC}, {\u0022_repeatMode\u0022, All}, {\u0022_displayMode\u0022, WithMultipleChunks, AnyOOC}, {\u0022_nth\u0022, 1}, {\u0022_offset\u0022, 1}, {\u0022_text\u0022, }}","_continuationMarker":"(#c/#m)","_markLastChunk":"True","_scratchMaxTextLen":"4096","_scratchInputLineHeight":"5","_newAliasSelection":"0","_newAlias":"","_newAliasTarget":"","_headerAliases":"{ \u0022\u0022 }","_fixDoubleSpace":"True","_dictionaryFilename":"web: lang_en","_maxSuggestions":"5","_autospellcheck":"True","_autospellcheckdelay":"1","_punctuationCleaningString":",.:;\u0027*\u0022(){}[]!?\u003C\u003E\u0060~\u2665@#$%^\u0026*_=\u002B\\\\/\u2190\u2192\u2191\u2193\u300A\u300B\u25A0\u203B\u2600\u2605\u2605\u2606\u2661\u30C5\u30C4\u30C3\u30B7\u2600\u2601\u2602\u2103\u2109\u00B0\u2640\u2642\u2660\u2663\u2666\u2663\u2667\u00AE\u00A9\u2122\u20AC$\u00A3\u266F\u266D\u266A\u2713\u221A\u25CE\u25C6\u25C7\u2666\u25A0\u25A1\u3007\u25CF\u25B3\u25BD\u25BC\u25B2\u2039\u203A\u2264\u2265\u003C\u00AB\u201C\u201D\u2500\uFF3C\uFF5E\uE04F","_cwlinkshells":"[ \u00221, \u00222, \u00223, \u00224, \u00225, \u00226, \u00227, \u00228\u0022 ]","_linkshells":"[ \u00221, \u00222, \u00223, \u00224, \u00225, \u00226, \u00227, \u00228\u0022 ]","_backupColor":"\u003C0, 0, 0, 0\u003E","_enableTextColor":"True","_spellingErrorColor":"\u003C0.9, 0.2, 0.2, 1\u003E","_headerColors":"","_style":"ImGuiNET.ImGuiStylePtr","MAX_MARKER_FRAME_Y":"10","Exception":{"Error":"System.InvalidCastException: Unable to cast object of type \u0027Wordsmith.Gui.SettingsUI\u0027 to type \u0027Wordsmith.Gui.ScratchPadUI\u0027.\r\n   at Wordsmith.Gui.SettingsUI.DrawScratchPadTab() in /work/repo/Wordsmith/Gui/SettingsUI.cs:line 174\r\n   at Wordsmith.Gui.SettingsUI.Draw() in /work/repo/Wordsmith/Gui/SettingsUI.cs:line 113","Message":"Unable to cast object of type \u0027Wordsmith.Gui.SettingsUI\u0027 to type \u0027Wordsmith.Gui.ScratchPadUI\u0027."},"Window":"SettingsUI"}

**Comment by MythicPalette** [comment]
Thank you for reporting this! It looks like it attempted to load the settings UI as a scratchpad in the list which definitely is not intended. I'll get to work on this right away. ♥

**Comment by MythicPalette** [comment]
I spoke too soon. Reading the error, that's what I thought it was, but after tracing the issue, I see what the real problem is now. Having the Settings window open and clicking "close all" causes it to attempt to close all windows, including the settings window. It should (obviously) not be working like this. I just needed to filter out the SettingsUI before attempting to close all windows. Thank you for finding this bug!

**Comment by birdo-birdson** [comment]
I'm glad I could help! By the way, as a fellow dev, your system for posting error logs and bug reports is great! Makes it really easy to send these things in, minimal effort required on the user. Might need to talk to my team about implementing something similar in the future...

**Comment by MythicPalette** [comment]
Well thank you! Bug reporting is important and most people won't bother if it's too difficult so I set out to make it as easy as possible.
