### ISSUE TITLE
I'm not sure if this is the right place to post this, but I noticed 'hsi' doesn't pop up as misspelled 'his' with spellchecker, it just considers it a normal word.  I googled it to see if it might be, but it doesn't look like it is!

### ISSUE THREAD

**Issue by CrazedSadeyr** [MythicPalette/Wordsmith-DalamudPlugin#55]
I'm not entirely sure if it is a more obscure word or a bug, but I noticed the spellchecker doesn't recognize 'hsi' as a misspell!

**Comment by MythicPalette** [comment]
I didn't write the dictionary file so there are weird cases like this in several spots. It seems that "HSI" is an abbreviation for "Health & Safety Institute". Probably not something many people in FFXIV are writing, lol. I'll remove it from the dictionary in a moment.
